name: Publish to crates.io
on:
  push:
    # Triggers when pushing tags starting with 'rust-v'
    tags: ["rust-v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: rust-release
    permissions:
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@v5
      - name: Verify publish crate
        run: cargo publish --dry-run

      - name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
